version: '3.8'

services:
  postgres-test:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: via_forum_test
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres-test:5432/via_forum_test"
      SECRET_KEY: test-secret-key
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: "10080"
      FRONTEND_URL: http://localhost:3000
      ENVIRONMENT: test
    volumes:
      - .:/app
    depends_on:
      postgres-test:
        condition: service_healthy
    command: pytest -v --tb=short