name: Run Tests

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-all:
    name: Run All Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    # Frontend tests
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install frontend dependencies
      working-directory: frontend
      run: npm ci
    
    - name: Run frontend tests
      working-directory: frontend
      run: |
        npm run typecheck
        npm test -- --run --reporter=verbose
    
    # Backend tests
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install backend dependencies
      working-directory: backend
      run: |
        pip install -r requirements.txt
        pip install -r requirements-test.txt
    
    - name: Run backend tests
      working-directory: backend
      run: |
        pytest -v --tb=short
    
    - name: Test Summary
      if: always()
      run: |
        echo "✅ Tests completed!"
        echo "Check the logs above for detailed results."